services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - API_KEY=AIzaSyAHSHmZBWu0YBLRu0GE80WUuyb_X-LQ8HM
    volumes:
      - ./backend:/main